export const todoConstants =  {
    GET_ALL_TODOS_REQUEST: "GET_ALL_TODOS_REQUEST",
    GET_ALL_TODOS_SUCCESS: "GET_ALL_TODOS_SUCCESS", 
    GET_ALL_TODOS_FAILURE: "GET_ALL_TODOS_FAILURE",
    DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST", 
    DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS", 
    DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",
    CREATE_TODO_REQUEST: "CREATE_TODO_REQUEST", 
    CREATE_TODO_SUCCESS: "CREATE_TODO_SUCCESS",
    CREATE_TODO_FAILURE: "CREATE_TODO_FAILURE"
}